// Generated by CoffeeScript 1.3.3
(function() {
  var Mandala, MandalaAttrs;

  MandalaAttrs = Backbone.Model.extend({
    defaults: {
      id: 'canvas',
      width: 600,
      height: 600,
      num_circles: 8,
      step: 0.005,
      offset: 0.0,
      go: true
    },
    initialize: function() {
      return this.set({
        mid: {
          x: this.get('width') / 2,
          y: this.get('height') / 2
        },
        avg: (this.get('height') + this.get('width')) / 2
      });
    },
    inc: function() {
      return this.set({
        offset: this.get('offset') + this.get('step')
      });
    }
  });

  Mandala = (function() {

    function Mandala(id) {
      this.attrs = new MandalaAttrs({
        id: id
      });
      this.canvas_el = $("#" + this.attrs.id).get(0);
      this.canvas = this.canvas_el.getContext('2d');
      this.go();
    }

    Mandala.prototype.go = function() {
      return setTimeout((function(mandala) {
        mandala.draw();
        return mandala.attrs.inc();
      }), 1000.0 / 30.0, this);
    };

    Mandala.prototype.draw = function() {
      var angle, i, x, y, _i, _ref;
      this.canvas.clearRect(0, 0, this.attrs.get('height'), this.attrs.get('width'));
      this.canvas.beginPath();
      for (i = _i = 0, _ref = this.attrs.get('num_circles') - 1; 0 <= _ref ? _i <= _ref : _i >= _ref; i = 0 <= _ref ? ++_i : --_i) {
        angle = ((2.0 * Math.PI / this.attrs.get('num_circles')) * i) + this.attrs.get('offset');
        x = this.attrs.get('avg') / 3 * Math.sin(angle);
        y = this.attrs.get('avg') / 3 * Math.cos(angle);
        this.canvas.beginPath();
        this.canvas.arc(this.attrs.get('mid').x + x, this.attrs.get('mid').y + y, this.attrs.get('avg') / 15, 0, 2.0 * Math.PI);
        this.canvas.stroke();
      }
      if (this.attrs.get('go')) {
        return this.go();
      }
    };

    return Mandala;

  })();

  $(window).ready(function() {
    var m;
    return m = new Mandala('mandala-canvas');
  });

}).call(this);
